
server {
	listen 0.0.0.0:8082;

	root /home/mjaouchi/goinfre/www;
	error_page 404 /errorPage/404.html;

	location / {
		index index.html;
		autoindex on;
		client_max_body_size 100000;
		allow_methods GET POST DELETE;
		cgi_pass .pl /usr/bin/perl;
		cgi_pass .py /usr/bin/python3;

		upload_location /uploads/;
		upload_store /home/mjaouchi/goinfre/www;
	}

	location /cgi-bin
	{
		allow_methods GET;
		
		index index.php;
	}
	location /uploads/
	{
		allow_methods GET;
	}

	location /forbiden/
	{
		autoindex off;
	}

	location /google
	{
		allow_methods GET;
		return 302 https://www.google.com;
		
	}
	location /intra
	{
		allow_methods GET;
		return 301 https://profile.intra.42.fr/;
	}
	index index.html;

}
